/*
==============================================================================

g_human grunt

==============================================================================
*/

$modelname valve/models/g_hgrunt.mdl
$cd valve/models/hgrunt
$cdtexture valve/models/german_models/german_hgrunt

$scale 1.0

$root "Bip01"

// whole body
$body body "../german_models/german_hgrunt/g_hgrunt"

$include "valve/models/hgrunt/hgrunt_shared.qc"