/*
==============================================================================

german human heavy weapons

==============================================================================
*/

$modelname valve/models/g_heavy.mdl
$cd valve/models/hvyweapons
$cdtexture valve/models/german_models/german_heavy

$scale 1.0

// whole body
$body studio "../german_models/german_heavy/g_heavy"

//$body studio "gunreference"

$include "valve/models/hvyweapons/heavy_shared.qc"